// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMessageData, AddMessageErrors, AddMessageResponses, RetrieveMemoryData, RetrieveMemoryErrors, RetrieveMemoryRawData, RetrieveMemoryRawErrors, RetrieveMemoryRawResponses, RetrieveMemoryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Add a message to a conversation
 */
export const addMessage = <ThrowOnError extends boolean = false>(options: Options<AddMessageData, ThrowOnError>) => (options.client ?? client).post<AddMessageResponses, AddMessageErrors, ThrowOnError>({
    url: '/api/v0/add_message',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve memories formatted as markdown for LLM consumption
 */
export const retrieveMemory = <ThrowOnError extends boolean = false>(options: Options<RetrieveMemoryData, ThrowOnError>) => (options.client ?? client).post<RetrieveMemoryResponses, RetrieveMemoryErrors, ThrowOnError>({
    url: '/api/v0/retrieve_memory',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve memories in raw JSON format
 */
export const retrieveMemoryRaw = <ThrowOnError extends boolean = false>(options: Options<RetrieveMemoryRawData, ThrowOnError>) => (options.client ?? client).post<RetrieveMemoryRawResponses, RetrieveMemoryRawErrors, ThrowOnError>({
    url: '/api/v0/retrieve_memory/raw',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
