//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation_message")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub conversation_id: Uuid,
  pub seq: i64,
  pub role: String,
  pub content: String,
  pub timestamp: DateTimeWithTimeZone,
  pub created_at: DateTimeWithTimeZone,
  pub source: Option<String>,
  pub import_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
