//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[expect(clippy::derive_partial_eq_without_eq, reason = "generated")]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation_message")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub conversation_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub seq: i64,
  #[sea_orm(column_type = "Text")]
  pub role: String,
  #[sea_orm(column_type = "Text")]
  pub content: String,
  pub timestamp: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
