//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "episodic_memory")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub conversation_id: Uuid,
  #[sea_orm(column_type = "JsonBinary")]
  pub messages: Json,
  #[sea_orm(column_type = "Text")]
  pub summary: String,
  pub embedding: PgVector,
  #[sea_orm(column_type = "Text")]
  pub title: String,
  #[sea_orm(column_type = "Float")]
  pub stability: f32,
  #[sea_orm(column_type = "Float")]
  pub difficulty: f32,
  #[sea_orm(column_type = "Float")]
  pub surprise: f32,
  pub start_at: DateTimeWithTimeZone,
  pub end_at: DateTimeWithTimeZone,
  pub created_at: DateTimeWithTimeZone,
  pub last_reviewed_at: DateTimeWithTimeZone,
  pub consolidated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
