//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::EpisodeClassification;

#[expect(clippy::derive_partial_eq_without_eq, reason = "generated")]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "episode_span")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub conversation_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub start_seq: i64,
  pub end_seq: i64,
  pub classification: EpisodeClassification,
  pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
