//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[expect(clippy::derive_partial_eq_without_eq, reason = "generated")]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "message_queue")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  #[sea_orm(column_type = "JsonBinary")]
  pub messages: Json,
  #[sea_orm(column_type = "JsonBinary", nullable)]
  pub pending_reviews: Option<Json>,
  pub in_progress_fence: Option<i32>,
  pub in_progress_since: Option<DateTimeWithTimeZone>,
  pub prev_episode_content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
