//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[expect(clippy::derive_partial_eq_without_eq, reason = "generated")]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "pending_review_queue")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub conversation_id: Uuid,
  #[sea_orm(column_type = "Text")]
  pub query: String,
  pub memory_ids: Vec<Uuid>,
  pub created_at: DateTimeWithTimeZone,
  pub consumed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
