//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "segmentation_state")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub conversation_id: Uuid,
  pub next_message_seq: i64,
  pub next_unsegmented_seq: i64,
  pub open_tail_start_seq: Option<i64>,
  pub last_seen_seq: Option<i64>,
  pub eof_seen: bool,
  pub in_progress_until_seq: Option<i64>,
  pub in_progress_since: Option<DateTimeWithTimeZone>,
  #[sea_orm(column_type = "JsonBinary", nullable)]
  pub last_closed_boundary_context: Option<Json>,
  pub strategy_version: String,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
