//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[expect(clippy::derive_partial_eq_without_eq, reason = "generated")]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "segmentation_state")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub conversation_id: Uuid,
  pub last_message_seq: i64,
  pub eof_identified: bool,
  pub next_segment_start_seq: i64,
  pub active_segment_start_seq: Option<i64>,
  pub active_segment_end_seq: Option<i64>,
  pub active_since: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
