//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "semantic_memory")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub conversation_id: Uuid,
  #[sea_orm(column_type = "Text")]
  pub subject: String,
  #[sea_orm(column_type = "Text")]
  pub predicate: String,
  #[sea_orm(column_type = "Text")]
  pub object: String,
  #[sea_orm(column_type = "Text")]
  pub fact: String,
  pub source_episodic_ids: Vec<Uuid>,
  pub valid_at: DateTimeWithTimeZone,
  pub invalid_at: Option<DateTimeWithTimeZone>,
  pub embedding: PgVector,
  pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
